"use client"
import './globals.css'
import '../styles/global.css';
import { Navbar, Footer } from '@/components'
import Head from 'next/head'

//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MyStore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Navbar/>
        {children}
        <Footer />
        </body>
    </html>
  )
}
